"""Semantic analysis module for knowledge curation via classical NLP.

This module provides TF-IDF vectorization, LSA, similarity analysis, and quality metrics
for document chunks generated by the chunking pipeline.

Components:
- TF-IDF vectorization engine with intelligent caching
- Document and chunk similarity analysis
- Latent Semantic Analysis (LSA) implementation
- Quality metrics integration with textstat
- Similarity analysis CLI command and reporting

Type Contract: List[Chunk] → ProcessingResult (with semantic analysis)
"""

from typing import TYPE_CHECKING

# Version and module metadata
__version__ = "1.0.0"
__all__ = [
    "TfidfVectorizationStage",
    "TfidfConfig",
    "SemanticResult",
    "CacheManager",
]

# Lazy imports to avoid circular dependencies
if TYPE_CHECKING:
    from .cache import CacheManager
    from .models import SemanticResult
    from .tfidf import TfidfConfig, TfidfVectorizationStage
